language: node_js

node_js: 10

cache:
  directories:
  - "$HOME/.npm"

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run semantic-release
